<?php
/*
 * Generated by WikiPEG
 */





// Grammar.php is automatically generated from Grammar.pegphp

// UNDERSTANDING OR MODIFYING THIS FILE ISN'T REQUIRED TO COMPLETE
// THE GIVEN TASKS.

namespace Wikimedia\LittleWikitext\Parser;

use Wikimedia\LittleWikitext\AST\Heading;
use Wikimedia\LittleWikitext\AST\Inclusion;
use Wikimedia\LittleWikitext\AST\Link;
use Wikimedia\LittleWikitext\AST\ListItem;
use Wikimedia\LittleWikitext\AST\Node;
use Wikimedia\LittleWikitext\AST\Paragraph;
use Wikimedia\LittleWikitext\AST\Root;
use Wikimedia\LittleWikitext\AST\Section;
use Wikimedia\LittleWikitext\AST\Text;

// File-scope initializers




class Grammar extends \Wikimedia\WikiPEG\PEGParserBase {
	// initializer
	
	// Class-scope initializers

	/**
	 * @param string $contents
	 * @return Root
	 */
	public static function load( string $contents ): Root {
		$g = new Grammar();
		return $g->parse( $contents );
	}


	// cache init
	

	// expectations
	protected $expectations = [
		0 => ["type" => "end", "description" => "end of input"],
1 => ["type" => "other", "description" => "section"],
2 => ["type" => "other", "description" => "heading"],
3 => ["type" => "literal", "value" => "*", "description" => "\"*\""],
4 => ["type" => "other", "description" => "inline"],
5 => ["type" => "other", "description" => "eol"],
6 => ["type" => "literal", "value" => "==", "description" => "\"==\""],
7 => ["type" => "other", "description" => "link"],
8 => ["type" => "other", "description" => "template"],
9 => ["type" => "class", "value" => "[^\\n\\r]", "description" => "[^\\n\\r]"],
10 => ["type" => "literal", "value" => "[[", "description" => "\"[[\""],
11 => ["type" => "class", "value" => "[^\\n\\r] but not \"|\"", "description" => "[^\\n\\r] but not \"|\""],
12 => ["type" => "literal", "value" => "|", "description" => "\"|\""],
13 => ["type" => "literal", "value" => "]]", "description" => "\"]]\""],
14 => ["type" => "literal", "value" => "{{", "description" => "\"{{\""],
15 => ["type" => "literal", "value" => "}}", "description" => "\"}}\""],
	];

	// actions
	private function a0($s, $children) {

	if ($s !== null) {
		array_unshift( $children, $s );
	}
	return new Root( $children );

}
private function a1($children) {

	return new Section( null, $children );

}
private function a2($h, $children) {

	return new Section( $h, $children );

}
private function a3($level, $txt) {

	if ( count( $level ) === 0 ) {
		// Plain text, not a list item
		return new Paragraph( Node::normalize( $txt ) );
	} else {
		return new ListItem( count( $level ), Node::trim( $txt ) );
	}

}
private function a4($txt) {

	return new Heading( Node::trim( $txt ) );

}
private function a5($c) {
 return new Text( $c ); 
}
private function a6($target, $caption) {

	$target = trim( implode( '', $target ) );
	return new Link( $target, Node::trim( $caption ) );

}
private function a7($target) {

	$target = trim( implode( '', $target ) );
	return new Inclusion( $target );

}

	// generated
	private function parsestart($silence) {
  $p2 = $this->currPos;
  // start seq_1
  $r3 = $this->parseunnamed_section($silence);
  if ($r3===self::$FAILED) {
    $r3 = null;
  }
  // s <- $r3
  $r4 = [];
  for (;;) {
    // start seq_2
    $p6 = $this->currPos;
    $r7 = $this->input[$this->currPos] ?? '';
    if ($r7 === "=") {
      $r7 = false;
      $this->currPos = $p6;
    } else {
      $r7 = self::$FAILED;
      if (!$silence) { $this->fail(1); }
      $r5 = self::$FAILED;
      goto seq_2;
    }
    $r5 = $this->parsesection($silence);
    if ($r5===self::$FAILED) {
      $this->currPos = $p6;
      $r5 = self::$FAILED;
      goto seq_2;
    }
    seq_2:
    if ($r5!==self::$FAILED) {
      $r4[] = $r5;
    } else {
      break;
    }
    // free $p6
  }
  // children <- $r4
  // free $r5
  // free $r7
  $r1 = true;
  seq_1:
  $this->savedPos = $p2;
  $r1 = $this->a0($r3, $r4);
  // free $p2
  return $r1;
}
private function parseunnamed_section($silence) {
  $p2 = $this->currPos;
  $r3 = [];
  for (;;) {
    $r4 = $this->parselist_or_para($silence);
    if ($r4!==self::$FAILED) {
      $r3[] = $r4;
    } else {
      break;
    }
  }
  if (count($r3) === 0) {
    $r3 = self::$FAILED;
  }
  // children <- $r3
  // free $r4
  $r1 = $r3;
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a1($r3);
  }
  // free $p2
  return $r1;
}
private function parsesection($silence) {
  $p2 = $this->currPos;
  // start seq_1
  $p3 = $this->currPos;
  // start seq_2
  $r5 = $this->input[$this->currPos] ?? '';
  if ($r5 === "=") {
    $r5 = false;
    $this->currPos = $p3;
  } else {
    $r5 = self::$FAILED;
    if (!$silence) { $this->fail(2); }
    $r4 = self::$FAILED;
    goto seq_2;
  }
  $r4 = $this->parseheading($silence);
  if ($r4===self::$FAILED) {
    $this->currPos = $p3;
    $r4 = self::$FAILED;
    goto seq_2;
  }
  seq_2:
  // h <- $r4
  if ($r4===self::$FAILED) {
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r6 = [];
  for (;;) {
    $r7 = $this->parselist_or_para($silence);
    if ($r7!==self::$FAILED) {
      $r6[] = $r7;
    } else {
      break;
    }
  }
  // children <- $r6
  // free $r7
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a2($r4, $r6);
  }
  // free $r5
  // free $p3
  // free $p2
  return $r1;
}
private function parselist_or_para($silence) {
  $p2 = $this->currPos;
  // start seq_1
  $p3 = $this->currPos;
  $p5 = $this->currPos;
  if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "==", $this->currPos, 2, false) === 0) {
    $r4 = true;
  } else {
    $r4 = self::$FAILED;
  }
  if ($r4 === self::$FAILED) {
    $r4 = false;
  } else {
    $r4 = self::$FAILED;
    $this->currPos = $p5;
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  // free $p5
  $r6 = [];
  for (;;) {
    if (($this->input[$this->currPos] ?? null) === "*") {
      $r7 = "*";
      $this->currPos++;
      $r6[] = $r7;
    } else {
      if (!$silence) { $this->fail(3); }
      $r7 = self::$FAILED;
      break;
    }
  }
  // level <- $r6
  // free $r7
  $r7 = [];
  for (;;) {
    // start seq_2
    $p5 = $this->currPos;
    $r9 = self::charAt($this->input, $this->currPos);
    if ($r9 !== '' && !($r9 === "\x0a" || $r9 === "\x0d")) {
      $r9 = false;
      $this->currPos = $p5;
    } else {
      $r9 = self::$FAILED;
      if (!$silence) { $this->fail(4); }
      $r8 = self::$FAILED;
      goto seq_2;
    }
    $r8 = $this->parseinline($silence);
    if ($r8===self::$FAILED) {
      $this->currPos = $p5;
      $r8 = self::$FAILED;
      goto seq_2;
    }
    seq_2:
    if ($r8!==self::$FAILED) {
      $r7[] = $r8;
    } else {
      break;
    }
    // free $p5
  }
  // txt <- $r7
  // free $r8
  // free $r9
  // start seq_3
  $p5 = $this->currPos;
  $r8 = $this->input[$this->currPos] ?? '';
  if ($r8 === "\x0a" || $r8 === "\x0d") {
    $r8 = false;
    $this->currPos = $p5;
  } else {
    $r8 = self::$FAILED;
    if (!$silence) { $this->fail(5); }
    $r9 = self::$FAILED;
    goto seq_3;
  }
  $r9 = $this->discardeol();
  if ($r9===self::$FAILED) {
    $this->currPos = $p5;
    $r9 = self::$FAILED;
    goto seq_3;
  }
  seq_3:
  if ($r9===self::$FAILED) {
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  // free $p5
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a3($r6, $r7);
  }
  // free $r4,$r9,$r8
  // free $p3
  // free $p2
  return $r1;
}
private function parseheading($silence) {
  $p2 = $this->currPos;
  // start seq_1
  $p3 = $this->currPos;
  if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "==", $this->currPos, 2, false) === 0) {
    $r4 = true;
    $this->currPos += 2;
  } else {
    if (!$silence) { $this->fail(6); }
    $r4 = self::$FAILED;
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r5 = [];
  for (;;) {
    // start seq_2
    $p7 = $this->currPos;
    if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "==", $this->currPos, 2, false) === 0) {
      $r8 = true;
    } else {
      $r8 = self::$FAILED;
    }
    if ($r8 === self::$FAILED) {
      $r8 = false;
    } else {
      $r8 = self::$FAILED;
      $this->currPos = $p7;
      $r6 = self::$FAILED;
      goto seq_2;
    }
    // start seq_3
    $p9 = $this->currPos;
    $r10 = self::charAt($this->input, $this->currPos);
    if ($r10 !== '' && !($r10 === "\x0a" || $r10 === "\x0d")) {
      $r10 = false;
      $this->currPos = $p9;
    } else {
      $r10 = self::$FAILED;
      if (!$silence) { $this->fail(4); }
      $r6 = self::$FAILED;
      goto seq_3;
    }
    $r6 = $this->parseinline($silence);
    if ($r6===self::$FAILED) {
      $this->currPos = $p9;
      $r6 = self::$FAILED;
      goto seq_3;
    }
    seq_3:
    if ($r6===self::$FAILED) {
      $this->currPos = $p7;
      $r6 = self::$FAILED;
      goto seq_2;
    }
    // free $p9
    seq_2:
    if ($r6!==self::$FAILED) {
      $r5[] = $r6;
    } else {
      break;
    }
    // free $r10
    // free $p7
  }
  if (count($r5) === 0) {
    $r5 = self::$FAILED;
  }
  // txt <- $r5
  if ($r5===self::$FAILED) {
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  // free $r6
  if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "==", $this->currPos, 2, false) === 0) {
    $r6 = true;
    $this->currPos += 2;
  } else {
    if (!$silence) { $this->fail(6); }
    $r6 = self::$FAILED;
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  // start seq_4
  $p7 = $this->currPos;
  $r11 = $this->input[$this->currPos] ?? '';
  if ($r11 === "\x0a" || $r11 === "\x0d") {
    $r11 = false;
    $this->currPos = $p7;
  } else {
    $r11 = self::$FAILED;
    if (!$silence) { $this->fail(5); }
    $r10 = self::$FAILED;
    goto seq_4;
  }
  $r10 = $this->discardeol();
  if ($r10===self::$FAILED) {
    $this->currPos = $p7;
    $r10 = self::$FAILED;
    goto seq_4;
  }
  seq_4:
  if ($r10===self::$FAILED) {
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  // free $p7
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a4($r5);
  }
  // free $r4,$r6,$r10,$r11
  // free $p3
  // free $p2
  return $r1;
}
private function parseinline($silence) {
  // start choice_1
  // start seq_1
  $p2 = $this->currPos;
  $r3 = $this->input[$this->currPos] ?? '';
  if ($r3 === "[") {
    $r3 = false;
    $this->currPos = $p2;
  } else {
    $r3 = self::$FAILED;
    if (!$silence) { $this->fail(7); }
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r1 = $this->parselink($silence);
  if ($r1===self::$FAILED) {
    $this->currPos = $p2;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  seq_1:
  if ($r1!==self::$FAILED) {
    goto choice_1;
  }
  // free $p2
  // start seq_2
  $p2 = $this->currPos;
  $r4 = $this->input[$this->currPos] ?? '';
  if ($r4 === "{") {
    $r4 = false;
    $this->currPos = $p2;
  } else {
    $r4 = self::$FAILED;
    if (!$silence) { $this->fail(8); }
    $r1 = self::$FAILED;
    goto seq_2;
  }
  $r1 = $this->parsetemplate($silence);
  if ($r1===self::$FAILED) {
    $this->currPos = $p2;
    $r1 = self::$FAILED;
    goto seq_2;
  }
  seq_2:
  if ($r1!==self::$FAILED) {
    goto choice_1;
  }
  // free $p2
  $p2 = $this->currPos;
  $r5 = self::charAt($this->input, $this->currPos);
  // c <- $r5
  if ($r5 !== '' && !($r5 === "\x0a" || $r5 === "\x0d")) {
    $this->currPos += strlen($r5);
  } else {
    $r5 = self::$FAILED;
    if (!$silence) { $this->fail(9); }
  }
  $r1 = $r5;
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a5($r5);
  }
  // free $p2
  choice_1:
  return $r1;
}
private function discardeol() {
  // start choice_1
  // start seq_1
  $p2 = $this->currPos;
  $r3 = $this->input[$this->currPos] ?? '';
  if ($r3 === "\x0d") {
    $this->currPos++;
  } else {
    $r3 = self::$FAILED;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r4 = $this->input[$this->currPos] ?? '';
  if ($r4 === "\x0a") {
    $this->currPos++;
  } else {
    $r4 = self::$FAILED;
    $r4 = null;
  }
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    goto choice_1;
  }
  // free $r3,$r4
  // free $p2
  if (($this->input[$this->currPos] ?? null) === "\x0a") {
    $r1 = true;
    $this->currPos++;
  } else {
    $r1 = self::$FAILED;
  }
  choice_1:
  return $r1;
}
private function parselink($silence) {
  $p2 = $this->currPos;
  // start seq_1
  $p3 = $this->currPos;
  if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "[[", $this->currPos, 2, false) === 0) {
    $r4 = true;
    $this->currPos += 2;
  } else {
    if (!$silence) { $this->fail(10); }
    $r4 = self::$FAILED;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r5 = strcspn($this->input, "\x0a\x0d|", $this->currPos);
  // target <- $r5
  if ($r5 > 0) {
    $this->currPos += $r5;
    $r5 = substr($this->input, $this->currPos - $r5, $r5);
    $r5 = mb_str_split($r5, 1, "utf-8");
  } else {
    $r5 = self::$FAILED;
    if (!$silence) { $this->fail(11); }
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  if (($this->input[$this->currPos] ?? null) === "|") {
    $r6 = true;
    $this->currPos++;
  } else {
    if (!$silence) { $this->fail(12); }
    $r6 = self::$FAILED;
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r7 = [];
  for (;;) {
    // start seq_2
    $p9 = $this->currPos;
    // start choice_1
    if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "[[", $this->currPos, 2, false) === 0) {
      $r10 = true;
      goto choice_1;
    } else {
      $r10 = self::$FAILED;
    }
    if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "]]", $this->currPos, 2, false) === 0) {
      $r10 = true;
    } else {
      $r10 = self::$FAILED;
    }
    choice_1:
    if ($r10 === self::$FAILED) {
      $r10 = false;
    } else {
      $r10 = self::$FAILED;
      $this->currPos = $p9;
      $r8 = self::$FAILED;
      goto seq_2;
    }
    // start seq_3
    $p11 = $this->currPos;
    $r12 = self::charAt($this->input, $this->currPos);
    if ($r12 !== '' && !($r12 === "\x0a" || $r12 === "\x0d")) {
      $r12 = false;
      $this->currPos = $p11;
    } else {
      $r12 = self::$FAILED;
      if (!$silence) { $this->fail(4); }
      $r8 = self::$FAILED;
      goto seq_3;
    }
    $r8 = $this->parseinline($silence);
    if ($r8===self::$FAILED) {
      $this->currPos = $p11;
      $r8 = self::$FAILED;
      goto seq_3;
    }
    seq_3:
    if ($r8===self::$FAILED) {
      $this->currPos = $p9;
      $r8 = self::$FAILED;
      goto seq_2;
    }
    // free $p11
    seq_2:
    if ($r8!==self::$FAILED) {
      $r7[] = $r8;
    } else {
      break;
    }
    // free $r12
    // free $p9
  }
  // caption <- $r7
  // free $r8
  // free $r10
  if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "]]", $this->currPos, 2, false) === 0) {
    $r10 = true;
    $this->currPos += 2;
  } else {
    if (!$silence) { $this->fail(13); }
    $r10 = self::$FAILED;
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a6($r5, $r7);
  }
  // free $r4,$r6,$r10
  // free $p3
  // free $p2
  return $r1;
}
private function parsetemplate($silence) {
  $p2 = $this->currPos;
  // start seq_1
  $p3 = $this->currPos;
  if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "{{", $this->currPos, 2, false) === 0) {
    $r4 = true;
    $this->currPos += 2;
  } else {
    if (!$silence) { $this->fail(14); }
    $r4 = self::$FAILED;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r5 = [];
  for (;;) {
    // start seq_2
    $p7 = $this->currPos;
    if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "}}", $this->currPos, 2, false) === 0) {
      $r8 = true;
    } else {
      $r8 = self::$FAILED;
    }
    if ($r8 === self::$FAILED) {
      $r8 = false;
    } else {
      $r8 = self::$FAILED;
      $this->currPos = $p7;
      $r6 = self::$FAILED;
      goto seq_2;
    }
    $r6 = self::charAt($this->input, $this->currPos);
    if ($r6 !== '' && !($r6 === "\x0a" || $r6 === "\x0d")) {
      $this->currPos += strlen($r6);
    } else {
      $r6 = self::$FAILED;
      if (!$silence) { $this->fail(9); }
      $this->currPos = $p7;
      $r6 = self::$FAILED;
      goto seq_2;
    }
    seq_2:
    if ($r6!==self::$FAILED) {
      $r5[] = $r6;
    } else {
      break;
    }
    // free $p7
  }
  if (count($r5) === 0) {
    $r5 = self::$FAILED;
  }
  // target <- $r5
  if ($r5===self::$FAILED) {
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  // free $r6
  if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "}}", $this->currPos, 2, false) === 0) {
    $r6 = true;
    $this->currPos += 2;
  } else {
    if (!$silence) { $this->fail(15); }
    $r6 = self::$FAILED;
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a7($r5);
  }
  // free $r4,$r6
  // free $p3
  // free $p2
  return $r1;
}

	public function parse( $input, $options = [] ) {
		$this->initInternal( $input, $options );
		$startRule = $options['startRule'] ?? '(DEFAULT)';
		$result = null;

		if ( !empty( $options['stream'] ) ) {
			switch ( $startRule ) {
				
			default:
				throw new \Wikimedia\WikiPEG\InternalError( "Can't stream rule $startRule." );
			}
		} else {
			switch ( $startRule ) {
				case '(DEFAULT)':
case "start":
  $result = $this->parsestart(false);
  break;
			default:
				throw new \Wikimedia\WikiPEG\InternalError( "Can't start parsing from rule $startRule." );
			}
		}

		if ( $result !== self::$FAILED && $this->currPos === $this->inputLength ) {
			return $result;
		} else {
			if ( $result !== self::$FAILED && $this->currPos < $this->inputLength ) {
				$this->fail( 0 );
			}
			throw $this->buildParseException();
		}
	}
}

