<?php
/*
 * Generated by WikiPEG
 */





/* File-scope initializer */
namespace Wikimedia\LittleWikitext\Tests\ParserTests;




class Grammar extends \Wikimedia\WikiPEG\PEGParserBase {
	// initializer
	
	/** @var string */
	private $filename = '';
	/** @var int */
	private $lineNum = 1;

	/**
	 * @param string $filename
	 * @return array
	 */
	public static function load( string $filename ) {
		$g = new Grammar();
		$g->filename = $filename;
		$contents = file_get_contents( $filename ) ?: '';
		if ( substr( $contents, -1 ) !== "\n" ) {
			# ensure that the file is terminated with a newline
			# to match `end_section` rule (and other uses of `eol`)
			$contents .= "\n";
		}
		return $g->parse( $contents );
	}


	// cache init
	

	// expectations
	protected $expectations = [
		0 => ["type" => "end", "description" => "end of input"],
1 => ["type" => "other", "description" => "comment"],
2 => ["type" => "other", "description" => "test"],
3 => ["type" => "literal", "value" => "#", "description" => "\"#\""],
4 => ["type" => "other", "description" => "start_test"],
5 => ["type" => "other", "description" => "section"],
6 => ["type" => "other", "description" => "option_section"],
7 => ["type" => "other", "description" => "end_section"],
8 => ["type" => "class", "value" => "[^\\r\\n]", "description" => "[^\\r\\n]"],
9 => ["type" => "other", "description" => "eol"],
10 => ["type" => "literal", "value" => "!!", "description" => "\"!!\""],
11 => ["type" => "class", "value" => "[ \\t]", "description" => "[ \\t]"],
12 => ["type" => "class", "value" => "[^ \\t\\r\\n]", "description" => "[^ \\t\\r\\n]"],
13 => ["type" => "literal", "value" => "options", "description" => "\"options\""],
14 => ["type" => "other", "description" => "option_list"],
15 => ["type" => "other", "description" => "an_option"],
16 => ["type" => "other", "description" => "option_name"],
17 => ["type" => "other", "description" => "option_value"],
18 => ["type" => "class", "value" => "[^ \\t\\r\\n=!]", "description" => "[^ \\t\\r\\n=!]"],
19 => ["type" => "literal", "value" => "=", "description" => "\"=\""],
20 => ["type" => "other", "description" => "option_value_list"],
21 => ["type" => "other", "description" => "an_option_value"],
22 => ["type" => "literal", "value" => ",", "description" => "\",\""],
23 => ["type" => "other", "description" => "link_target_value"],
24 => ["type" => "other", "description" => "quoted_value"],
25 => ["type" => "other", "description" => "plain_value"],
26 => ["type" => "other", "description" => "json_value"],
27 => ["type" => "literal", "value" => "[[", "description" => "\"[[\""],
28 => ["type" => "class", "value" => "[^\\]\\r\\n]", "description" => "[^\\]\\r\\n]"],
29 => ["type" => "literal", "value" => "]]", "description" => "\"]]\""],
30 => ["type" => "class", "value" => "[\\\"]", "description" => "[\\\"]"],
31 => ["type" => "class", "value" => "[^\\\\\\\"\\r\\n]", "description" => "[^\\\\\\\"\\r\\n]"],
32 => ["type" => "literal", "value" => "\\", "description" => "\"\\\\\""],
33 => ["type" => "class", "value" => "[^ \\t\\r\\n\\\"\\'\\[\\]=,!\\{]", "description" => "[^ \\t\\r\\n\\\"\\'\\[\\]=,!\\{]"],
34 => ["type" => "literal", "value" => "{", "description" => "\"{\""],
35 => ["type" => "class", "value" => "[^\\\"\\{\\}\\r\\n]", "description" => "[^\\\"\\{\\}\\r\\n]"],
36 => ["type" => "literal", "value" => "}", "description" => "\"}\""],
37 => ["type" => "class", "value" => "[\\r]", "description" => "[\\r]"],
38 => ["type" => "class", "value" => "[\\n]", "description" => "[\\n]"],
39 => ["type" => "literal", "value" => "\x0a", "description" => "\"\\n\""],
	];

	// actions
	private function a0() {
 return $this->lineNum; 
}
private function a1($l, $c) {

	$c['filename'] = $this->filename;
	$c['lineNumStart'] = $l;
	$c['lineNumEnd'] = $this->lineNum;
	return $c;

}
private function a2($l) {
 return [ 'type' => 'line', 'text' => $l ]; 
}
private function a3($text) {
 return [ 'type' => 'comment', 'text' => $text ]; 
}
private function a4($testName, $sections) {

	$test = [
		'type' => 'test',
		'testName' => $testName
	];

	foreach ( $sections as $section ) {
		$test[$section['name']] = $section['text'];
	}
	// pegjs parser handles item options as follows:
	//   item option             value of item.options.parsoid
	//    <none>                          undefined
	//    parsoid                             ""
	//    parsoid=wt2html                  "wt2html"
	//    parsoid=wt2html,wt2wt        ["wt2html","wt2wt"]
	//    parsoid={"modes":["wt2wt"]}    {modes:['wt2wt']}

	return $test;

}
private function a5($line) {

	return $line;

}
private function a6($c) {

	return implode($c);

}
private function a7($lines) {

	$lines[] = ''; // Ensure \n after last line
	return implode("\n", $lines);

}
private function a8($name, $text) {

	return [ 'name' => $name, 'text' => $text ];

}
private function a9($opts) {

	$o = [];
	if ( $opts && count($opts) > 0 ) {
		foreach ( $opts as $opt ) {
			$o[$opt['k']] = $opt['v'];
		}
	}

	return [ 'name' => 'options', 'text' => $o ];

}
private function a10() {
 $this->lineNum++; return "\n"; 
}
private function a11($o, $rest) {

	$result = [ $o ];
	if ( $rest && count( $rest ) > 0 ) {
		$result = array_merge( $result, $rest );
	}
	return $result;

}
private function a12($k, $v) {

	return [ 'k' => strtolower( $k ), 'v' => $v ?? '' ];

}
private function a13($c) {

	return $c;

}
private function a14($ovl) {

	return count( $ovl ) === 1 ? $ovl[0] : $ovl;

}
private function a15($v, $rest) {

	$result = [ $v ];
	if ( $rest && count( $rest ) > 0 ) {
		$result = array_merge( $result, $rest );
	}
	return $result;

}
private function a16($v) {

	if ( $v[0] === '"' || $v[0] === '{' ) { // } is needed to make pegjs happy
		return json_decode( $v, true );
	}
	return $v;

}
private function a17($v) {

	// Perhaps we should canonicalize the title?
	// Protect with JSON.stringify just in case the link target starts with
	// double-quote or open-brace.
	return json_encode( $v, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE );

}
private function a18($c) {
 return "\\" . $c; 
}
private function a19($v) {

	return '"' . implode( $v ) . '"';

}
private function a20($v) {

	return $v;

}
private function a21($v) {

	return "{" . implode( $v ) . "}";

}

	// generated
	private function parsetestfile($silence) {
  $r1 = [];
  for (;;) {
    $r2 = $this->parselined_chunk($silence);
    if ($r2!==self::$FAILED) {
      $r1[] = $r2;
    } else {
      break;
    }
  }
  if (count($r1) === 0) {
    $r1 = self::$FAILED;
  }
  // free $r2
  return $r1;
}
private function parselined_chunk($silence) {
  $p2 = $this->currPos;
  // start seq_1
  $p3 = $this->currPos;
  $r4 = true;
  // l <- $r4
  $this->savedPos = $p3;
  $r4 = $this->a0();
  $r5 = $this->parsechunk($silence);
  // c <- $r5
  if ($r5===self::$FAILED) {
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a1($r4, $r5);
  }
  // free $p3
  // free $p2
  return $r1;
}
private function parsechunk($silence) {
  // start choice_1
  // start seq_1
  $p2 = $this->currPos;
  $r3 = $this->input[$this->currPos] ?? '';
  if ($r3 === "#") {
    $r3 = false;
    $this->currPos = $p2;
  } else {
    $r3 = self::$FAILED;
    if (!$silence) { $this->fail(1); }
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r1 = $this->parsecomment($silence);
  if ($r1===self::$FAILED) {
    $this->currPos = $p2;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  seq_1:
  if ($r1!==self::$FAILED) {
    goto choice_1;
  }
  // free $p2
  // start seq_2
  $p2 = $this->currPos;
  $r4 = $this->input[$this->currPos] ?? '';
  if ($r4 === "!") {
    $r4 = false;
    $this->currPos = $p2;
  } else {
    $r4 = self::$FAILED;
    if (!$silence) { $this->fail(2); }
    $r1 = self::$FAILED;
    goto seq_2;
  }
  $r1 = $this->parsetest($silence);
  if ($r1===self::$FAILED) {
    $this->currPos = $p2;
    $r1 = self::$FAILED;
    goto seq_2;
  }
  seq_2:
  if ($r1!==self::$FAILED) {
    goto choice_1;
  }
  // free $p2
  $p2 = $this->currPos;
  $r5 = $this->parseline($silence);
  // l <- $r5
  $r1 = $r5;
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a2($r5);
  }
  // free $p2
  choice_1:
  return $r1;
}
private function parsecomment($silence) {
  $p2 = $this->currPos;
  // start seq_1
  $p3 = $this->currPos;
  if (($this->input[$this->currPos] ?? null) === "#") {
    $r4 = true;
    $this->currPos++;
  } else {
    if (!$silence) { $this->fail(3); }
    $r4 = self::$FAILED;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r5 = $this->parserest_of_line($silence);
  // text <- $r5
  if ($r5===self::$FAILED) {
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a3($r5);
  }
  // free $r4
  // free $p3
  // free $p2
  return $r1;
}
private function parsetest($silence) {
  $p2 = $this->currPos;
  // start seq_1
  $p3 = $this->currPos;
  // start seq_2
  $r5 = $this->input[$this->currPos] ?? '';
  if ($r5 === "!") {
    $r5 = false;
    $this->currPos = $p3;
  } else {
    $r5 = self::$FAILED;
    if (!$silence) { $this->fail(4); }
    $r4 = self::$FAILED;
    goto seq_2;
  }
  $r4 = $this->discardstart_test();
  if ($r4===self::$FAILED) {
    $this->currPos = $p3;
    $r4 = self::$FAILED;
    goto seq_2;
  }
  seq_2:
  if ($r4===self::$FAILED) {
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r6 = $this->parsetext($silence);
  // testName <- $r6
  $r7 = [];
  for (;;) {
    // start choice_1
    // start seq_3
    $p9 = $this->currPos;
    $r10 = $this->input[$this->currPos] ?? '';
    if ($r10 === "!") {
      $r10 = false;
      $this->currPos = $p9;
    } else {
      $r10 = self::$FAILED;
      if (!$silence) { $this->fail(5); }
      $r8 = self::$FAILED;
      goto seq_3;
    }
    $r8 = $this->parsesection($silence);
    if ($r8===self::$FAILED) {
      $this->currPos = $p9;
      $r8 = self::$FAILED;
      goto seq_3;
    }
    seq_3:
    if ($r8!==self::$FAILED) {
      goto choice_1;
    }
    // free $p9
    // start seq_4
    $p9 = $this->currPos;
    $r11 = $this->input[$this->currPos] ?? '';
    if ($r11 === "!") {
      $r11 = false;
      $this->currPos = $p9;
    } else {
      $r11 = self::$FAILED;
      if (!$silence) { $this->fail(6); }
      $r8 = self::$FAILED;
      goto seq_4;
    }
    $r8 = $this->parseoption_section($silence);
    if ($r8===self::$FAILED) {
      $this->currPos = $p9;
      $r8 = self::$FAILED;
      goto seq_4;
    }
    seq_4:
    // free $p9
    choice_1:
    if ($r8!==self::$FAILED) {
      $r7[] = $r8;
    } else {
      break;
    }
  }
  // sections <- $r7
  // free $r8
  // free $r10,$r11
  // start seq_5
  $p9 = $this->currPos;
  $r10 = $this->input[$this->currPos] ?? '';
  if ($r10 === "!") {
    $r10 = false;
    $this->currPos = $p9;
  } else {
    $r10 = self::$FAILED;
    if (!$silence) { $this->fail(7); }
    $r11 = self::$FAILED;
    goto seq_5;
  }
  $r11 = $this->discardend_section();
  if ($r11===self::$FAILED) {
    $this->currPos = $p9;
    $r11 = self::$FAILED;
    goto seq_5;
  }
  seq_5:
  if ($r11===self::$FAILED) {
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  // free $p9
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a4($r6, $r7);
  }
  // free $r4,$r5,$r11,$r10
  // free $p3
  // free $p2
  return $r1;
}
private function parseline($silence) {
  $p2 = $this->currPos;
  // start seq_1
  $p3 = $this->currPos;
  if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "!!", $this->currPos, 2, false) === 0) {
    $r4 = true;
  } else {
    $r4 = self::$FAILED;
  }
  if ($r4 === self::$FAILED) {
    $r4 = false;
  } else {
    $r4 = self::$FAILED;
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r5 = $this->parserest_of_line($silence);
  // line <- $r5
  if ($r5===self::$FAILED) {
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a5($r5);
  }
  // free $r4
  // free $p3
  // free $p2
  return $r1;
}
private function parserest_of_line($silence) {
  $p2 = $this->currPos;
  // start seq_1
  $p3 = $this->currPos;
  $r4 = strcspn($this->input, "\x0a\x0d", $this->currPos);
  // c <- $r4
  $this->currPos += $r4;
  $r4 = substr($this->input, $this->currPos - $r4, $r4);
  $r4 = mb_str_split($r4, 1, "utf-8");
  // start seq_2
  $p6 = $this->currPos;
  $r7 = $this->input[$this->currPos] ?? '';
  if ($r7 === "\x0a" || $r7 === "\x0d") {
    $r7 = false;
    $this->currPos = $p6;
  } else {
    $r7 = self::$FAILED;
    if (!$silence) { $this->fail(9); }
    $r5 = self::$FAILED;
    goto seq_2;
  }
  $r5 = $this->discardeol();
  if ($r5===self::$FAILED) {
    $this->currPos = $p6;
    $r5 = self::$FAILED;
    goto seq_2;
  }
  seq_2:
  if ($r5===self::$FAILED) {
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  // free $p6
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a6($r4);
  }
  // free $r5,$r7
  // free $p3
  // free $p2
  return $r1;
}
private function discardstart_test() {
  // start seq_1
  $p2 = $this->currPos;
  if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "!!", $this->currPos, 2, false) === 0) {
    $r3 = true;
    $this->currPos += 2;
  } else {
    $r3 = self::$FAILED;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r4 = strspn($this->input, "\x09 ", $this->currPos);
  if ($r4 > 0) {
    $this->currPos += $r4;
  } else {
    $r4 = self::$FAILED;
    $r4 = null;
  }
  if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "test", $this->currPos, 4, false) === 0) {
    $r5 = true;
    $this->currPos += 4;
  } else {
    $r5 = self::$FAILED;
    $this->currPos = $p2;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r6 = strspn($this->input, "\x09 ", $this->currPos);
  if ($r6 > 0) {
    $this->currPos += $r6;
  } else {
    $r6 = self::$FAILED;
    $r6 = null;
  }
  // start seq_2
  $p8 = $this->currPos;
  $r9 = $this->input[$this->currPos] ?? '';
  if ($r9 === "\x0a" || $r9 === "\x0d") {
    $r9 = false;
    $this->currPos = $p8;
  } else {
    $r9 = self::$FAILED;
    $r7 = self::$FAILED;
    goto seq_2;
  }
  $r7 = $this->discardeol();
  if ($r7===self::$FAILED) {
    $this->currPos = $p8;
    $r7 = self::$FAILED;
    goto seq_2;
  }
  seq_2:
  if ($r7===self::$FAILED) {
    $this->currPos = $p2;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  // free $p8
  $r1 = true;
  seq_1:
  // free $r3,$r4,$r5,$r6,$r7,$r9
  // free $p2
  return $r1;
}
private function parsetext($silence) {
  $p2 = $this->currPos;
  $r3 = [];
  for (;;) {
    $r4 = $this->parseline($silence);
    if ($r4!==self::$FAILED) {
      $r3[] = $r4;
    } else {
      break;
    }
  }
  // lines <- $r3
  // free $r4
  $r1 = $r3;
  $this->savedPos = $p2;
  $r1 = $this->a7($r3);
  // free $p2
  return $r1;
}
private function parsesection($silence) {
  $p2 = $this->currPos;
  // start seq_1
  $p3 = $this->currPos;
  if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "!!", $this->currPos, 2, false) === 0) {
    $r4 = true;
    $this->currPos += 2;
  } else {
    if (!$silence) { $this->fail(10); }
    $r4 = self::$FAILED;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r5 = strspn($this->input, "\x09 ", $this->currPos);
  if ($r5 > 0) {
    $this->currPos += $r5;
  } else {
    $r5 = self::$FAILED;
    if (!$silence) { $this->fail(11); }
    $r5 = null;
  }
  $p7 = $this->currPos;
  if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "end", $this->currPos, 3, false) === 0) {
    $r6 = true;
  } else {
    $r6 = self::$FAILED;
  }
  if ($r6 === self::$FAILED) {
    $r6 = false;
  } else {
    $r6 = self::$FAILED;
    $this->currPos = $p7;
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  // free $p7
  $p7 = $this->currPos;
  if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "options", $this->currPos, 7, false) === 0) {
    $r8 = true;
  } else {
    $r8 = self::$FAILED;
  }
  if ($r8 === self::$FAILED) {
    $r8 = false;
  } else {
    $r8 = self::$FAILED;
    $this->currPos = $p7;
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  // free $p7
  $p7 = $this->currPos;
  $r9 = strcspn($this->input, "\x09\x0a\x0d ", $this->currPos);
  // name <- $r9
  if ($r9 > 0) {
    $this->currPos += $r9;
    $r9 = substr($this->input, $p7, $this->currPos - $p7);
  } else {
    $r9 = self::$FAILED;
    if (!$silence) { $this->fail(12); }
    $r9 = self::$FAILED;
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  // free $p7
  $r10 = $this->discardrest_of_line();
  if ($r10===self::$FAILED) {
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r11 = $this->parsetext($silence);
  // text <- $r11
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a8($r9, $r11);
  }
  // free $r4,$r5,$r6,$r8,$r10
  // free $p3
  // free $p2
  return $r1;
}
private function parseoption_section($silence) {
  $p2 = $this->currPos;
  // start seq_1
  $p3 = $this->currPos;
  if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "!!", $this->currPos, 2, false) === 0) {
    $r4 = true;
    $this->currPos += 2;
  } else {
    if (!$silence) { $this->fail(10); }
    $r4 = self::$FAILED;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r5 = strspn($this->input, "\x09 ", $this->currPos);
  if ($r5 > 0) {
    $this->currPos += $r5;
  } else {
    $r5 = self::$FAILED;
    if (!$silence) { $this->fail(11); }
    $r5 = null;
  }
  if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "options", $this->currPos, 7, false) === 0) {
    $r6 = true;
    $this->currPos += 7;
  } else {
    if (!$silence) { $this->fail(13); }
    $r6 = self::$FAILED;
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r7 = strspn($this->input, "\x09 ", $this->currPos);
  if ($r7 > 0) {
    $this->currPos += $r7;
  } else {
    $r7 = self::$FAILED;
    if (!$silence) { $this->fail(11); }
    $r7 = null;
  }
  // start seq_2
  $p9 = $this->currPos;
  $r10 = $this->input[$this->currPos] ?? '';
  if ($r10 === "\x0a" || $r10 === "\x0d") {
    $r10 = false;
    $this->currPos = $p9;
  } else {
    $r10 = self::$FAILED;
    if (!$silence) { $this->fail(9); }
    $r8 = self::$FAILED;
    goto seq_2;
  }
  $r8 = $this->discardeol();
  if ($r8===self::$FAILED) {
    $this->currPos = $p9;
    $r8 = self::$FAILED;
    goto seq_2;
  }
  seq_2:
  if ($r8===self::$FAILED) {
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  // free $p9
  // start seq_3
  $p9 = $this->currPos;
  if (strcspn($this->input, "\x09\x0a\x0d !=", $this->currPos, 1) !== 0) {
    $r12 = true;
    $r12 = false;
    $this->currPos = $p9;
  } else {
    $r12 = self::$FAILED;
    if (!$silence) { $this->fail(14); }
    $r11 = self::$FAILED;
    goto seq_3;
  }
  $r11 = $this->parseoption_list($silence);
  if ($r11===self::$FAILED) {
    $this->currPos = $p9;
    $r11 = self::$FAILED;
    goto seq_3;
  }
  seq_3:
  if ($r11===self::$FAILED) {
    $r11 = null;
  }
  // free $p9
  // opts <- $r11
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a9($r11);
  }
  // free $r4,$r5,$r6,$r7,$r8,$r10,$r12
  // free $p3
  // free $p2
  return $r1;
}
private function discardend_section() {
  // start seq_1
  $p2 = $this->currPos;
  if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "!!", $this->currPos, 2, false) === 0) {
    $r3 = true;
    $this->currPos += 2;
  } else {
    $r3 = self::$FAILED;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r4 = strspn($this->input, "\x09 ", $this->currPos);
  if ($r4 > 0) {
    $this->currPos += $r4;
  } else {
    $r4 = self::$FAILED;
    $r4 = null;
  }
  if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "end", $this->currPos, 3, false) === 0) {
    $r5 = true;
    $this->currPos += 3;
  } else {
    $r5 = self::$FAILED;
    $this->currPos = $p2;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r6 = strspn($this->input, "\x09 ", $this->currPos);
  if ($r6 > 0) {
    $this->currPos += $r6;
  } else {
    $r6 = self::$FAILED;
    $r6 = null;
  }
  // start seq_2
  $p8 = $this->currPos;
  $r9 = $this->input[$this->currPos] ?? '';
  if ($r9 === "\x0a" || $r9 === "\x0d") {
    $r9 = false;
    $this->currPos = $p8;
  } else {
    $r9 = self::$FAILED;
    $r7 = self::$FAILED;
    goto seq_2;
  }
  $r7 = $this->discardeol();
  if ($r7===self::$FAILED) {
    $this->currPos = $p8;
    $r7 = self::$FAILED;
    goto seq_2;
  }
  seq_2:
  if ($r7===self::$FAILED) {
    $this->currPos = $p2;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  // free $p8
  $r1 = true;
  seq_1:
  // free $r3,$r4,$r5,$r6,$r7,$r9
  // free $p2
  return $r1;
}
private function discardeol() {
  $p2 = $this->currPos;
  // start choice_1
  // start seq_1
  $p3 = $this->currPos;
  $r4 = $this->input[$this->currPos] ?? '';
  if ($r4 === "\x0d") {
    $this->currPos++;
  } else {
    $r4 = self::$FAILED;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r5 = $this->input[$this->currPos] ?? '';
  if ($r5 === "\x0a") {
    $this->currPos++;
  } else {
    $r5 = self::$FAILED;
    $r5 = null;
  }
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    goto choice_1;
  }
  // free $r4,$r5
  // free $p3
  if (($this->input[$this->currPos] ?? null) === "\x0a") {
    $r1 = true;
    $this->currPos++;
  } else {
    $r1 = self::$FAILED;
  }
  choice_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a10();
  }
  // free $p2
  return $r1;
}
private function discardrest_of_line() {
  $p2 = $this->currPos;
  // start seq_1
  $p3 = $this->currPos;
  $r4 = strcspn($this->input, "\x0a\x0d", $this->currPos);
  // c <- $r4
  $this->currPos += $r4;
  $r4 = substr($this->input, $this->currPos - $r4, $r4);
  $r4 = mb_str_split($r4, 1, "utf-8");
  // start seq_2
  $p6 = $this->currPos;
  $r7 = $this->input[$this->currPos] ?? '';
  if ($r7 === "\x0a" || $r7 === "\x0d") {
    $r7 = false;
    $this->currPos = $p6;
  } else {
    $r7 = self::$FAILED;
    $r5 = self::$FAILED;
    goto seq_2;
  }
  $r5 = $this->discardeol();
  if ($r5===self::$FAILED) {
    $this->currPos = $p6;
    $r5 = self::$FAILED;
    goto seq_2;
  }
  seq_2:
  if ($r5===self::$FAILED) {
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  // free $p6
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a6($r4);
  }
  // free $r5,$r7
  // free $p3
  // free $p2
  return $r1;
}
private function parseoption_list($silence) {
  $p2 = $this->currPos;
  // start seq_1
  $p3 = $this->currPos;
  // start seq_2
  if (strcspn($this->input, "\x09\x0a\x0d !=", $this->currPos, 1) !== 0) {
    $r5 = true;
    $r5 = false;
    $this->currPos = $p3;
  } else {
    $r5 = self::$FAILED;
    if (!$silence) { $this->fail(15); }
    $r4 = self::$FAILED;
    goto seq_2;
  }
  $r4 = $this->parsean_option($silence);
  if ($r4===self::$FAILED) {
    $this->currPos = $p3;
    $r4 = self::$FAILED;
    goto seq_2;
  }
  seq_2:
  // o <- $r4
  if ($r4===self::$FAILED) {
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r6 = self::$FAILED;
  for (;;) {
    // start choice_1
    $r7 = $this->input[$this->currPos] ?? '';
    if ($r7 === "\x09" || $r7 === " ") {
      $this->currPos++;
      goto choice_1;
    } else {
      $r7 = self::$FAILED;
      if (!$silence) { $this->fail(11); }
    }
    // start seq_3
    $p8 = $this->currPos;
    $r9 = $this->input[$this->currPos] ?? '';
    if ($r9 === "\x0a" || $r9 === "\x0d") {
      $r9 = false;
      $this->currPos = $p8;
    } else {
      $r9 = self::$FAILED;
      if (!$silence) { $this->fail(9); }
      $r7 = self::$FAILED;
      goto seq_3;
    }
    $r7 = $this->discardeol();
    if ($r7===self::$FAILED) {
      $this->currPos = $p8;
      $r7 = self::$FAILED;
      goto seq_3;
    }
    seq_3:
    // free $p8
    choice_1:
    if ($r7!==self::$FAILED) {
      $r6 = true;
    } else {
      break;
    }
  }
  if ($r6===self::$FAILED) {
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  // free $r7
  // start seq_4
  $p8 = $this->currPos;
  if (strcspn($this->input, "\x09\x0a\x0d !=", $this->currPos, 1) !== 0) {
    $r10 = true;
    $r10 = false;
    $this->currPos = $p8;
  } else {
    $r10 = self::$FAILED;
    if (!$silence) { $this->fail(14); }
    $r7 = self::$FAILED;
    goto seq_4;
  }
  $r7 = $this->parseoption_list($silence);
  if ($r7===self::$FAILED) {
    $this->currPos = $p8;
    $r7 = self::$FAILED;
    goto seq_4;
  }
  seq_4:
  if ($r7===self::$FAILED) {
    $r7 = null;
  }
  // free $p8
  // rest <- $r7
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a11($r4, $r7);
  }
  // free $r5,$r6,$r10
  // free $p3
  // free $p2
  return $r1;
}
private function parsean_option($silence) {
  $p2 = $this->currPos;
  // start seq_1
  $p3 = $this->currPos;
  // start seq_2
  if (strcspn($this->input, "\x09\x0a\x0d !=", $this->currPos, 1) !== 0) {
    $r5 = true;
    $r5 = false;
    $this->currPos = $p3;
  } else {
    $r5 = self::$FAILED;
    if (!$silence) { $this->fail(16); }
    $r4 = self::$FAILED;
    goto seq_2;
  }
  $r4 = $this->parseoption_name($silence);
  if ($r4===self::$FAILED) {
    $this->currPos = $p3;
    $r4 = self::$FAILED;
    goto seq_2;
  }
  seq_2:
  // k <- $r4
  if ($r4===self::$FAILED) {
    $r1 = self::$FAILED;
    goto seq_1;
  }
  // start seq_3
  $p7 = $this->currPos;
  if (strspn($this->input, "\x09 =", $this->currPos, 1) !== 0) {
    $r8 = true;
    $r8 = false;
    $this->currPos = $p7;
  } else {
    $r8 = self::$FAILED;
    if (!$silence) { $this->fail(17); }
    $r6 = self::$FAILED;
    goto seq_3;
  }
  $r6 = $this->parseoption_value($silence);
  if ($r6===self::$FAILED) {
    $this->currPos = $p7;
    $r6 = self::$FAILED;
    goto seq_3;
  }
  seq_3:
  if ($r6===self::$FAILED) {
    $r6 = null;
  }
  // free $p7
  // v <- $r6
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a12($r4, $r6);
  }
  // free $r5,$r8
  // free $p3
  // free $p2
  return $r1;
}
private function parseoption_name($silence) {
  $p2 = $this->currPos;
  $p4 = $this->currPos;
  $r3 = strcspn($this->input, "\x09\x0a\x0d !=", $this->currPos);
  // c <- $r3
  if ($r3 > 0) {
    $this->currPos += $r3;
    $r3 = substr($this->input, $p4, $this->currPos - $p4);
  } else {
    $r3 = self::$FAILED;
    if (!$silence) { $this->fail(18); }
    $r3 = self::$FAILED;
  }
  // free $p4
  $r1 = $r3;
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a13($r3);
  }
  // free $p2
  return $r1;
}
private function parseoption_value($silence) {
  $p2 = $this->currPos;
  // start seq_1
  $p3 = $this->currPos;
  $r4 = strspn($this->input, "\x09 ", $this->currPos);
  if ($r4 > 0) {
    $this->currPos += $r4;
  } else {
    $r4 = self::$FAILED;
    if (!$silence) { $this->fail(11); }
    $r4 = null;
  }
  if (($this->input[$this->currPos] ?? null) === "=") {
    $r5 = true;
    $this->currPos++;
  } else {
    if (!$silence) { $this->fail(19); }
    $r5 = self::$FAILED;
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r6 = strspn($this->input, "\x09 ", $this->currPos);
  if ($r6 > 0) {
    $this->currPos += $r6;
  } else {
    $r6 = self::$FAILED;
    if (!$silence) { $this->fail(11); }
    $r6 = null;
  }
  // start seq_2
  $p8 = $this->currPos;
  if (strcspn($this->input, "\x09\x0a\x0d !',=]", $this->currPos, 1) !== 0) {
    $r9 = true;
    $r9 = false;
    $this->currPos = $p8;
  } else {
    $r9 = self::$FAILED;
    if (!$silence) { $this->fail(20); }
    $r7 = self::$FAILED;
    goto seq_2;
  }
  $r7 = $this->parseoption_value_list($silence);
  if ($r7===self::$FAILED) {
    $this->currPos = $p8;
    $r7 = self::$FAILED;
    goto seq_2;
  }
  seq_2:
  // ovl <- $r7
  if ($r7===self::$FAILED) {
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  // free $p8
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a14($r7);
  }
  // free $r4,$r5,$r6,$r9
  // free $p3
  // free $p2
  return $r1;
}
private function parseoption_value_list($silence) {
  $p2 = $this->currPos;
  // start seq_1
  $p3 = $this->currPos;
  // start seq_2
  if (strcspn($this->input, "\x09\x0a\x0d !',=]", $this->currPos, 1) !== 0) {
    $r5 = true;
    $r5 = false;
    $this->currPos = $p3;
  } else {
    $r5 = self::$FAILED;
    if (!$silence) { $this->fail(21); }
    $r4 = self::$FAILED;
    goto seq_2;
  }
  $r4 = $this->parsean_option_value($silence);
  if ($r4===self::$FAILED) {
    $this->currPos = $p3;
    $r4 = self::$FAILED;
    goto seq_2;
  }
  seq_2:
  // v <- $r4
  if ($r4===self::$FAILED) {
    $r1 = self::$FAILED;
    goto seq_1;
  }
  // start seq_3
  $p7 = $this->currPos;
  $r8 = strspn($this->input, "\x09 ", $this->currPos);
  if ($r8 > 0) {
    $this->currPos += $r8;
  } else {
    $r8 = self::$FAILED;
    if (!$silence) { $this->fail(11); }
    $r8 = null;
  }
  if (($this->input[$this->currPos] ?? null) === ",") {
    $r9 = true;
    $this->currPos++;
  } else {
    if (!$silence) { $this->fail(22); }
    $r9 = self::$FAILED;
    $this->currPos = $p7;
    $r6 = self::$FAILED;
    goto seq_3;
  }
  $r10 = strspn($this->input, "\x09 ", $this->currPos);
  if ($r10 > 0) {
    $this->currPos += $r10;
  } else {
    $r10 = self::$FAILED;
    if (!$silence) { $this->fail(11); }
    $r10 = null;
  }
  // start seq_4
  $p11 = $this->currPos;
  if (strcspn($this->input, "\x09\x0a\x0d !',=]", $this->currPos, 1) !== 0) {
    $r12 = true;
    $r12 = false;
    $this->currPos = $p11;
  } else {
    $r12 = self::$FAILED;
    if (!$silence) { $this->fail(20); }
    $r6 = self::$FAILED;
    goto seq_4;
  }
  $r6 = $this->parseoption_value_list($silence);
  if ($r6===self::$FAILED) {
    $this->currPos = $p11;
    $r6 = self::$FAILED;
    goto seq_4;
  }
  seq_4:
  if ($r6===self::$FAILED) {
    $this->currPos = $p7;
    $r6 = self::$FAILED;
    goto seq_3;
  }
  // free $p11
  seq_3:
  if ($r6===self::$FAILED) {
    $r6 = null;
  }
  // free $r12
  // free $p7
  // rest <- $r6
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a15($r4, $r6);
  }
  // free $r5,$r8,$r9,$r10
  // free $p3
  // free $p2
  return $r1;
}
private function parsean_option_value($silence) {
  $p2 = $this->currPos;
  // start choice_1
  // start seq_1
  $p4 = $this->currPos;
  $r5 = $this->input[$this->currPos] ?? '';
  if ($r5 === "[") {
    $r5 = false;
    $this->currPos = $p4;
  } else {
    $r5 = self::$FAILED;
    if (!$silence) { $this->fail(23); }
    $r3 = self::$FAILED;
    goto seq_1;
  }
  $r3 = $this->parselink_target_value($silence);
  if ($r3===self::$FAILED) {
    $this->currPos = $p4;
    $r3 = self::$FAILED;
    goto seq_1;
  }
  seq_1:
  if ($r3!==self::$FAILED) {
    goto choice_1;
  }
  // free $p4
  // start seq_2
  $p4 = $this->currPos;
  $r6 = $this->input[$this->currPos] ?? '';
  if ($r6 === "\"") {
    $r6 = false;
    $this->currPos = $p4;
  } else {
    $r6 = self::$FAILED;
    if (!$silence) { $this->fail(24); }
    $r3 = self::$FAILED;
    goto seq_2;
  }
  $r3 = $this->parsequoted_value($silence);
  if ($r3===self::$FAILED) {
    $this->currPos = $p4;
    $r3 = self::$FAILED;
    goto seq_2;
  }
  seq_2:
  if ($r3!==self::$FAILED) {
    goto choice_1;
  }
  // free $p4
  // start seq_3
  $p4 = $this->currPos;
  if (strcspn($this->input, "\x09\x0a\x0d !\"',=[]{", $this->currPos, 1) !== 0) {
    $r7 = true;
    $r7 = false;
    $this->currPos = $p4;
  } else {
    $r7 = self::$FAILED;
    if (!$silence) { $this->fail(25); }
    $r3 = self::$FAILED;
    goto seq_3;
  }
  $r3 = $this->parseplain_value($silence);
  if ($r3===self::$FAILED) {
    $this->currPos = $p4;
    $r3 = self::$FAILED;
    goto seq_3;
  }
  seq_3:
  if ($r3!==self::$FAILED) {
    goto choice_1;
  }
  // free $p4
  // start seq_4
  $p4 = $this->currPos;
  $r8 = $this->input[$this->currPos] ?? '';
  if ($r8 === "{") {
    $r8 = false;
    $this->currPos = $p4;
  } else {
    $r8 = self::$FAILED;
    if (!$silence) { $this->fail(26); }
    $r3 = self::$FAILED;
    goto seq_4;
  }
  $r3 = $this->parsejson_value($silence);
  if ($r3===self::$FAILED) {
    $this->currPos = $p4;
    $r3 = self::$FAILED;
    goto seq_4;
  }
  seq_4:
  // free $p4
  choice_1:
  // v <- $r3
  $r1 = $r3;
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a16($r3);
  }
  // free $r5,$r6,$r7,$r8
  // free $p2
  return $r1;
}
private function parselink_target_value($silence) {
  $p2 = $this->currPos;
  // start seq_1
  $p3 = $this->currPos;
  if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "[[", $this->currPos, 2, false) === 0) {
    $r4 = true;
    $this->currPos += 2;
  } else {
    if (!$silence) { $this->fail(27); }
    $r4 = self::$FAILED;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $p6 = $this->currPos;
  $r5 = strcspn($this->input, "\x0a\x0d]", $this->currPos);
  // v <- $r5
  $this->currPos += $r5;
  $r5 = substr($this->input, $p6, $this->currPos - $p6);
  // free $p6
  if ($this->currPos >= $this->inputLength ? false : substr_compare($this->input, "]]", $this->currPos, 2, false) === 0) {
    $r7 = true;
    $this->currPos += 2;
  } else {
    if (!$silence) { $this->fail(29); }
    $r7 = self::$FAILED;
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a17($r5);
  }
  // free $r4,$r7
  // free $p3
  // free $p2
  return $r1;
}
private function parsequoted_value($silence) {
  $p2 = $this->currPos;
  // start seq_1
  $p3 = $this->currPos;
  $r4 = $this->input[$this->currPos] ?? '';
  if ($r4 === "\"") {
    $this->currPos++;
  } else {
    $r4 = self::$FAILED;
    if (!$silence) { $this->fail(30); }
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r5 = [];
  for (;;) {
    // start choice_1
    if (strcspn($this->input, "\x0a\x0d\"\\", $this->currPos, 1) !== 0) {
      $r6 = self::consumeChar($this->input, $this->currPos);
      goto choice_1;
    } else {
      $r6 = self::$FAILED;
      if (!$silence) { $this->fail(31); }
    }
    $p7 = $this->currPos;
    // start seq_2
    $p8 = $this->currPos;
    if (($this->input[$this->currPos] ?? null) === "\\") {
      $r9 = true;
      $this->currPos++;
    } else {
      if (!$silence) { $this->fail(32); }
      $r9 = self::$FAILED;
      $r6 = self::$FAILED;
      goto seq_2;
    }
    $r10 = self::charAt($this->input, $this->currPos);
    // c <- $r10
    if ($r10 !== '' && !($r10 === "\x0a" || $r10 === "\x0d")) {
      $this->currPos += strlen($r10);
    } else {
      $r10 = self::$FAILED;
      if (!$silence) { $this->fail(8); }
      $this->currPos = $p8;
      $r6 = self::$FAILED;
      goto seq_2;
    }
    $r6 = true;
    seq_2:
    if ($r6!==self::$FAILED) {
      $this->savedPos = $p7;
      $r6 = $this->a18($r10);
    }
    // free $r9
    // free $p8
    // free $p7
    choice_1:
    if ($r6!==self::$FAILED) {
      $r5[] = $r6;
    } else {
      break;
    }
  }
  // v <- $r5
  // free $r6
  $r6 = $this->input[$this->currPos] ?? '';
  if ($r6 === "\"") {
    $this->currPos++;
  } else {
    $r6 = self::$FAILED;
    if (!$silence) { $this->fail(30); }
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a19($r5);
  }
  // free $r4,$r6
  // free $p3
  // free $p2
  return $r1;
}
private function parseplain_value($silence) {
  $p2 = $this->currPos;
  $p4 = $this->currPos;
  $r3 = strcspn($this->input, "\x09\x0a\x0d !\"',=[]{", $this->currPos);
  // v <- $r3
  if ($r3 > 0) {
    $this->currPos += $r3;
    $r3 = substr($this->input, $p4, $this->currPos - $p4);
  } else {
    $r3 = self::$FAILED;
    if (!$silence) { $this->fail(33); }
    $r3 = self::$FAILED;
  }
  // free $p4
  $r1 = $r3;
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a20($r3);
  }
  // free $p2
  return $r1;
}
private function parsejson_value($silence) {
  $p2 = $this->currPos;
  // start seq_1
  $p3 = $this->currPos;
  if (($this->input[$this->currPos] ?? null) === "{") {
    $r4 = true;
    $this->currPos++;
  } else {
    if (!$silence) { $this->fail(34); }
    $r4 = self::$FAILED;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r5 = [];
  for (;;) {
    // start choice_1
    if (strcspn($this->input, "\x0a\x0d\"{}", $this->currPos, 1) !== 0) {
      $r6 = self::consumeChar($this->input, $this->currPos);
      goto choice_1;
    } else {
      $r6 = self::$FAILED;
      if (!$silence) { $this->fail(35); }
    }
    // start seq_2
    $p7 = $this->currPos;
    $r8 = $this->input[$this->currPos] ?? '';
    if ($r8 === "\"") {
      $r8 = false;
      $this->currPos = $p7;
    } else {
      $r8 = self::$FAILED;
      if (!$silence) { $this->fail(24); }
      $r6 = self::$FAILED;
      goto seq_2;
    }
    $r6 = $this->parsequoted_value($silence);
    if ($r6===self::$FAILED) {
      $this->currPos = $p7;
      $r6 = self::$FAILED;
      goto seq_2;
    }
    seq_2:
    if ($r6!==self::$FAILED) {
      goto choice_1;
    }
    // free $p7
    // start seq_3
    $p7 = $this->currPos;
    $r9 = $this->input[$this->currPos] ?? '';
    if ($r9 === "{") {
      $r9 = false;
      $this->currPos = $p7;
    } else {
      $r9 = self::$FAILED;
      if (!$silence) { $this->fail(26); }
      $r6 = self::$FAILED;
      goto seq_3;
    }
    $r6 = $this->parsejson_value($silence);
    if ($r6===self::$FAILED) {
      $this->currPos = $p7;
      $r6 = self::$FAILED;
      goto seq_3;
    }
    seq_3:
    if ($r6!==self::$FAILED) {
      goto choice_1;
    }
    // free $p7
    // start seq_4
    $p7 = $this->currPos;
    $r10 = $this->input[$this->currPos] ?? '';
    if ($r10 === "\x0a" || $r10 === "\x0d") {
      $r10 = false;
      $this->currPos = $p7;
    } else {
      $r10 = self::$FAILED;
      if (!$silence) { $this->fail(9); }
      $r6 = self::$FAILED;
      goto seq_4;
    }
    $r6 = $this->parseeol($silence);
    if ($r6===self::$FAILED) {
      $this->currPos = $p7;
      $r6 = self::$FAILED;
      goto seq_4;
    }
    seq_4:
    // free $p7
    choice_1:
    if ($r6!==self::$FAILED) {
      $r5[] = $r6;
    } else {
      break;
    }
  }
  // v <- $r5
  // free $r6
  // free $r8,$r9,$r10
  if (($this->input[$this->currPos] ?? null) === "}") {
    $r10 = true;
    $this->currPos++;
  } else {
    if (!$silence) { $this->fail(36); }
    $r10 = self::$FAILED;
    $this->currPos = $p3;
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a21($r5);
  }
  // free $r4,$r10
  // free $p3
  // free $p2
  return $r1;
}
private function parseeol($silence) {
  $p2 = $this->currPos;
  // start choice_1
  // start seq_1
  $p3 = $this->currPos;
  $r4 = $this->input[$this->currPos] ?? '';
  if ($r4 === "\x0d") {
    $this->currPos++;
  } else {
    $r4 = self::$FAILED;
    if (!$silence) { $this->fail(37); }
    $r1 = self::$FAILED;
    goto seq_1;
  }
  $r5 = $this->input[$this->currPos] ?? '';
  if ($r5 === "\x0a") {
    $this->currPos++;
  } else {
    $r5 = self::$FAILED;
    if (!$silence) { $this->fail(38); }
    $r5 = null;
  }
  $r1 = true;
  seq_1:
  if ($r1!==self::$FAILED) {
    goto choice_1;
  }
  // free $r4,$r5
  // free $p3
  if (($this->input[$this->currPos] ?? null) === "\x0a") {
    $r1 = true;
    $this->currPos++;
  } else {
    if (!$silence) { $this->fail(39); }
    $r1 = self::$FAILED;
  }
  choice_1:
  if ($r1!==self::$FAILED) {
    $this->savedPos = $p2;
    $r1 = $this->a10();
  }
  // free $p2
  return $r1;
}

	public function parse( $input, $options = [] ) {
		$this->initInternal( $input, $options );
		$startRule = $options['startRule'] ?? '(DEFAULT)';
		$result = null;

		if ( !empty( $options['stream'] ) ) {
			switch ( $startRule ) {
				
			default:
				throw new \Wikimedia\WikiPEG\InternalError( "Can't stream rule $startRule." );
			}
		} else {
			switch ( $startRule ) {
				case '(DEFAULT)':
case "testfile":
  $result = $this->parsetestfile(false);
  break;
			default:
				throw new \Wikimedia\WikiPEG\InternalError( "Can't start parsing from rule $startRule." );
			}
		}

		if ( $result !== self::$FAILED && $this->currPos === $this->inputLength ) {
			return $result;
		} else {
			if ( $result !== self::$FAILED && $this->currPos < $this->inputLength ) {
				$this->fail( 0 );
			}
			throw $this->buildParseException();
		}
	}
}

